### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by Vistaus** [vchlum/nano-lights#1]
It would be great if this extension could be translated. Once possible, I'll provide the Dutch translation. 🙂

**Comment by vchlum** [comment]
Hi! The extension is translation-ready. It just needs to add the temptations. I will add them and you can translate.  Just a small warning: This extension is already ported to gnome 45, which means new versions will be provided only for gnome 45 and higher versions. This is due to upstream changes in gnome 45. Are you comfortable with it?

**Comment by Vistaus** [comment]
Hi! Yes, I'm comfortable with that.

**Comment by vchlum** [comment]
The template is ready. Feel free to raise PR with your favorite language:-)

**Comment by Vistaus** [comment]
Thanks, I'll start working on it! 🙂

**Comment by vchlum** [comment]
done
